# Generated by Django 2.2.25 on 2022-02-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220202_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
