# Generated by Django 2.2.25 on 2022-01-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220128_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profile/default.png', upload_to='images', verbose_name='プロフィール画面'),
        ),
    ]
