# Generated by Django 2.2.25 on 2022-02-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
