# Generated by Django 2.2.25 on 2022-02-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220202_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
